sudo: required
services:
  - docker


before_install:
  - docker build -t ifont21/pfeedback:dev -f Dockerfile.dev .


script:
  - docker run ifont21/pfeedback:dev npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "pfeedback"
#   env: "Pfeedback-env-1"
#   bucket_name: "elasticbeanstalk-us-east-1-843565894643"
#   bucket_path: "pfeedback"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY